### ISSUE TITLE
Menue is not available and implausible Measurement

### ISSUE THREAD

**Issue by kraukl** [davidkreidler/OpenCO2_Sensor#13]
On my CO2-Sensor its impossible to engage the menue. Pressing the button on the back near the on/off switch (in battery mode or loading mode) only toggles LED on/off. In my printed mini-manual this button is called No.7 "LED On/Off".
Obviously my device is not the model that is described and shown online now. On my device there is an additional Reset button No. 8 which forces an instant measurement. I tried several different combinations of managing the 3 switches No. 6,7,8 without getting in the menue.  

I wanted to update the device because the measurement behaviour is not sufficient. After storing in fresh air it shows 420-450 ppm and afterwords in the freshly ventilated room  it is creeping up implausibly quick and high. After moving it for testing into an airsealed and fresh air containing screwglass the CO2 raises up from initially 420 ppm to more than 2000ppm within 2 hours. It behaves in the sealed Glass as if its producing CO2 itself.

USB-Connection to my PC only affects a connection sound on the PC and no device shows up in the file manager.

I bougt the device at Tindie on 21 April 2023, Invoice No. #389420.
What can I do?

**Comment by davidkreidler** [comment]
Hello @kraukl and thanks for reaching out and testing already.

To enable the Menu please update to the latest release (because it was developed after your purchase):
Instructions: https://github.com/davidkreidler/OpenCO2_Sensor#update-via-usb

Step by step:
- Download all files from the latest [release](https://github.com/davidkreidler/OpenCO2_Sensor/releases)
- Make sure, that the power switch is in the ON position (down)
- Plug a data USB-C cable (not the magnetic one) into your PC and the Sensor
- Hold the Button on the backside of the CO2 Sensor near the USB-C port and shortly push simultaneously the reset ↪️ Button
- In Windows Device Manager (Gerätemanager) under Ports (COM & LPT) find the COM number and modify it in update.bat
- Run update.bat via double click 
- Afterwards push the reset ↪️ Button

This is only needed once. Afterwards or on new sensors its possible to update the Sensor over WiFi. 
If you have any questions please feel free to reach out.

After the update its possible to do a manual calibration via the Menu (please put the Sensor outside while doing so).
Generally the CO2 level can rise quite quickly depending on factors like: How big is the room, how high is the sealing, how airtight is the room, how many people are in the room and for how long it was ventilated. 
But you are right : during 2h in an air sealed container it should not rise. Only possibility I see is because CO2 is heavier then air it was collecting over time in the bottom close to the Sensor.

If these steps dont fix the observed behavior please reach out here and I will do an in depth analysis.
For this I then would like to kindly ask you to shipp the device to me. I will provide you a shipping label.

Thank you!
David

**Comment by kraukl** [comment]
Thankyou david,
the update now worked.

But the unplausible measurement is still lasting.

Attached my handwritten 30 hrs log of a test in an airsealed 150ml screwglass after calibration in fresh air.
The CO2-Display raised from initially 446ppm to a maximum of 1488ppm after 19hrs. 
Afterwards it gradually fell down furtheron to about constant 1000 to 1200ppm.

At first I assumed a faulty temperature compensation, but this obviously is not the reason (see temperatures & humidity values).

I would appreciate sending the device to you for a checkup as you kindly offered to me.

Best regards, manfred tischer

----------------------------------------------------------------------


Dienstag, 14. November 2023, 19:25:27, schriebst Du:

> Hello @kraukl and thanks for reaching out and testing already.

> To enable the Menu please update to the latest release (because it was developed after your purchase):
> Instructions: https://github.com/davidkreidler/OpenCO2_Sensor#update-via-usb

> Step by step:
> - Download all files from the latest [release](https://github.com/davidkreidler/OpenCO2_Sensor/releases)
> - Make sure, that the power switch is in the ON position (down)
> - Plug a data USB-C cable (not the magnetic one) into your PC and the Sensor
> - Hold the Button on the backside of the CO2 Sensor near the USB-C port and shortly push simultaneously the reset ↪️ Button
> - In Windows Device Manager (Gerätemanager) under Ports (COM & LPT) find the COM number and modify it in update.bat
> - Run update.bat via double click 
> - Afterwards push the reset ↪️ Button

> This is only needed once. Afterwards or on new sensors its possible to update the Sensor over WiFi. 
> If you have any questions please feel free to reach out.

> After the update its possible to do a manual calibration via the Menu (please put the Sensor outside while doing so).
> Generally the CO2 level can rise quite quickly depending on factors like: How big is the room, how high is the sealing, how airtight is the room, how many people are in the room and for how long it was ventilated. 
> But you are right : during 2h in an air sealed container it should not rise. Only possibility I see is because CO2 is heavier then air it was collecting over time in the bottom close to the Sensor.

> If these steps dont fix the observed behavior please reach out here and I will do an in depth analysis.
> For this I then would like to kindly ask you to shipp the device to me. I will provide you a shipping label.

> Thank you!
> David

**Comment by davidkreidler** [comment]
Evaluated the device and could not see a significant increase of CO2 inside a IKEA sealed container over 24h.
![image](https://github.com/davidkreidler/OpenCO2_Sensor/assets/13180124/92443600-3282-4d0d-9d10-10f6af187a9f)

Also a comparison to a 3rd party device and a second sensor showed a static difference (likely doe to calibration).
![image](https://github.com/davidkreidler/OpenCO2_Sensor/assets/13180124/a044e3ec-02da-47f4-9ccc-54e6281e4169)


One potential root cause of the increased CO2 Values was found in a call: The shift to colder temperatures because of the Winter season. This could have lead to a closed windows in the corridor. I will close the ticket for now.

**Comment by kraukl** [comment]
Danke, das Gerät ist angekommen.

Herzlichen Dank für Ihre Bemühungen

Manfred Tischer

-----------------------------------------------------------
Mittwoch, 29. November 2023, 23:48:48, schriebst Du:

> Evaluated the device and could not see a significant increase of CO2 inside a IKEA sealed container over 24h.
> ![image](https://github.com/davidkreidler/OpenCO2_Sensor/assets/13180124/92443600-3282-4d0d-9d10-10f6af187a9f)

> Also a comparison to a 3rd party device and a second sensor showed a static difference (likely doe to calibration).
> ![image](https://github.com/davidkreidler/OpenCO2_Sensor/assets/13180124/a044e3ec-02da-47f4-9ccc-54e6281e4169)


> One potential root cause of the increased CO2 Values was found in a call: The shift to colder temperatures because of the Winter season. This could have lead to a closed windows in the corridor. I will close the ticket for now.



-- 
Mit freundlichen Grüßen,
Manfred Tischer
