### ISSUE TITLE
Revised PCB

### ISSUE THREAD

**Issue by Blanketier** [davidkreidler/OpenCO2_Sensor#14]
I have run out of projects that I can make without spending an ungodly amount of money in R&D and me and a friend thought it would be fun if we mapped out the CO₂ monitor you have posted. You did not post the files for the schematic and board and only posted the images. looking at the schematic I have decided to just make a revised schematic with better power infrastructure and a few other misc. improvements. I was wondering if there is anyway to get in contact with you for you to explain some of your design choices?

**Comment by davidkreidler** [comment]
Hey here is a good player to ask questions and I would love to see the power infrastructure changes. Thanks! David

**Comment by Blanketier** [comment]
![image](https://github.com/davidkreidler/OpenCO2_Sensor/assets/146549006/21acb7c8-b3b3-435d-a3d6-8536f1280a82)
is the purpose of this section to switch between battery operated and usb powered depending on weather usb is plugged in?

**Comment by davidkreidler** [comment]
Yes and to detect if USB is plugged in to go out of battery mode.

**Comment by davidkreidler** [comment]
That's all parity Standart stuff. Almost every esp32 dev board uses these cheap components to protect the battery and only use it if USB is disconnected. The MOSFETs is conduction if USB is disconnected. And the diode otherwise powers the device. Using an expensive and not at my supplier lcsc available part is no improvement.
