### ISSUE TITLE
Several reboots during charging (v4.5)

### ISSUE THREAD

**Issue by nm** [davidkreidler/OpenCO2_Sensor#18]
After upgrading to v4.5, I have experienced several reboots during charging. Everything is fine in battery mode.
After downgrading to v4.4 the reboots are gone.

Does anyone else have this problem?
Maybe related to https://github.com/davidkreidler/OpenCO2_Sensor/commit/e351ebc04f1215ceaa1af4050829d22f6743a42b?

**Comment by davidkreidler** [comment]
Hey @nm thanks for updating to the latest version and sharing your experience. The commit you shared is only active in battery mode when going to deep sleep...

Most likely the instability is related to an updated ESP32 boards version to 
"Arduino Release v2.0.16 based on ESP-IDF v4.4.7".
arduino-esp32 https://github.com/espressif/arduino-esp32/compare/2.0.13...2.0.16

Here is a OpenCO2 v4.5 build based on ESP "Arduino Release v2.0.13":
https://drive.google.com/file/d/1mw3rHz8mlEjAy6Y1W7xySc4TDw19aKiD/view?usp=sharing

Would you please flash it and report back if the issue is fixed?

Thanks!
David

**Comment by nm** [comment]
Thanks @davidkreidler,
with the updated build the issue is fixed.

**Comment by davidkreidler** [comment]
Perfect thanks for confirming. I will debug this further.
